# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: "Personal PC"

variables:
- name: RG
  value: 'Lupo'
- name: RG_Location
  value: 'eastus'
- name: Vault
  value: 'lupo-keyvault-1'
- name: AppConfig
  value: 'lupo-appconfig-1'
- name: LogAnalytics
  value: 'LogAnalyticsName'
- name: InfrastructureFolder
  value: 'CloudInfrastructure'
- name: ApplicationInsight
  value: 'ApplicationInsight'
- name: LocalSQLDB
  value: 'Server=(localdb)\\MSSQLLocalDB;Database=MVC_local;Trusted_Connection=True;MultipleActiveResultSets=true'

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: ARM Deployment
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'ConnectionRGLupo'
      subscriptionId: 'fcd44864-d682-4d41-9c1b-745fe53c7410'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(RG)'
      location: '$(RG_Location)'
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.SourcesDirectory)\$(InfrastructureFolder)\azuredeploy.json'
      csmParametersFile: '$(Build.SourcesDirectory)\$(InfrastructureFolder)\azuredeploy.parameters.json'
      overrideParameters: '-location $(RG_Location) -VaultName $(Vault) -AppConfigName $(AppConfig) -LogAnalyticsName $(LogAnalytics) -ApplicationInsightName $(ApplicationInsight) -LocalDB $(LocalSQLDB)'
      deploymentMode: 'Incremental'
      deploymentOutputs: 'Deployment1'
  
  - script: |
      echo $(Deployment1)